### ISSUE TITLE
Create (or find) Makey with Mask art 

### ISSUE THREAD

**Issue by digitalman2112** [MakerFaireOrlando/mfo-static-website#29]
would be good for homepage section about 2020 and the make-a-mask workshop

Make may have already created one

![image](https://user-images.githubusercontent.com/452840/87247103-a9cc7300-c41f-11ea-8e0a-50e8bddc7959.png)

**Comment by makAR-rudy** [comment]
![Makey-in-a-mask](https://user-images.githubusercontent.com/56201692/87250504-53692f80-c433-11ea-8068-ae14f26aa87b.png)

What do you think?

**Comment by digitalman2112** [comment]
Looks great!

**Comment by makAR-rudy** [comment]
[Makey-in-a-mask.pdf](https://github.com/MakerFaireOrlando/mfo-static-website/files/4908777/Makey-in-a-mask.pdf)

OK here is the vectorized pdf version, do you want me to make a headshot icon like those other ones?

**Comment by digitalman2112** [comment]
If easy, could be nice to have the option

**Comment by makAR-rudy** [comment]
![Makey-in-a-mask-round](https://user-images.githubusercontent.com/56201692/87253833-3ee56100-c44c-11ea-8efe-126050b56215.png)
ok here we go, should we close the issue?

**Comment by digitalman2112** [comment]
I was thinking of framing him in one of these circles for the homepage - what do you think?
![image](https://user-images.githubusercontent.com/452840/87544517-97974280-c674-11ea-979a-8d71f020132a.png)

**Comment by digitalman2112** [comment]
I'm over masks. Let's call the pandemic "done" and close this issue (rolls eyes)
